"""empty message

Revision ID: 347451bd1ccc
Revises: 2e51dd18041e
Create Date: 2025-01-22 20:04:15.006074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '347451bd1ccc'
down_revision = '2e51dd18041e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_de_ojos_personaje', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('color_de_pelo_personaje', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('altura_de_personaje', sa.String(length=10), nullable=True))
        batch_op.drop_column('altra_personaje')
        batch_op.drop_column('color_pelo_personaje')
        batch_op.drop_column('color_ojos_personaje')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_ojos_personaje', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('color_pelo_personaje', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('altra_personaje', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.drop_column('altura_de_personaje')
        batch_op.drop_column('color_de_pelo_personaje')
        batch_op.drop_column('color_de_ojos_personaje')

    # ### end Alembic commands ###
