"""empty message

Revision ID: 4e64edd3faf2
Revises: 347451bd1ccc
Create Date: 2025-01-22 20:06:52.230081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e64edd3faf2'
down_revision = '347451bd1ccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poblacion_de_planeta', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('extension_de_planeta', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.drop_column('extension_de_planeta')
        batch_op.drop_column('poblacion_de_planeta')

    # ### end Alembic commands ###
