"""empty message

Revision ID: 749873f045a5
Revises: e941f1d873ce
Create Date: 2025-01-25 10:22:37.965730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '749873f045a5'
down_revision = 'e941f1d873ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contraseña', sa.String(length=20), nullable=False))
        batch_op.drop_column('contrasena')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contrasena', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_column('contraseña')

    # ### end Alembic commands ###
