"""empty message

Revision ID: 942cc67d2ee3
Revises: 4e64edd3faf2
Create Date: 2025-01-24 18:19:35.179578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '942cc67d2ee3'
down_revision = '4e64edd3faf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_de_ojos', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('color_de_pelo', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('altura_de', sa.String(length=10), nullable=True))
        batch_op.drop_column('altura_de_personaje')
        batch_op.drop_column('color_de_ojos_personaje')
        batch_op.drop_column('color_de_pelo_personaje')

    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poblacion', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('extension', sa.String(length=10), nullable=True))
        batch_op.drop_column('poblacion_de_planeta')
        batch_op.drop_column('extension_de_planeta')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extension_de_planeta', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('poblacion_de_planeta', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('extension')
        batch_op.drop_column('poblacion')

    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_de_pelo_personaje', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('color_de_ojos_personaje', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('altura_de_personaje', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.drop_column('altura_de')
        batch_op.drop_column('color_de_pelo')
        batch_op.drop_column('color_de_ojos')

    # ### end Alembic commands ###
