"""empty message

Revision ID: ded1eb0b10bb
Revises: 942cc67d2ee3
Create Date: 2025-01-24 19:04:04.466626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ded1eb0b10bb'
down_revision = '942cc67d2ee3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.alter_column('color_de_ojos',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('color_de_pelo',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('altura_de',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.alter_column('poblacion',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('extension',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('correo',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('contrasena',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.create_unique_constraint(None, ['correo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('contrasena',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('correo',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.alter_column('extension',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('poblacion',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.alter_column('altura_de',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('color_de_pelo',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('color_de_ojos',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
