"""empty message

Revision ID: e941f1d873ce
Revises: ded1eb0b10bb
Create Date: 2025-01-24 19:33:59.176780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e941f1d873ce'
down_revision = 'ded1eb0b10bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint('usuarios_correo_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_unique_constraint('usuarios_correo_key', ['correo'])

    # ### end Alembic commands ###
